version: "3.8"
services: 
  sql-server-db:
    container_name: sql-server-db
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: imstupid
     
     
    volumes:
    - dados:/var/lib/mysql/
 
  

volumes:
  dados:
    external: true
    



